import type { Metadata } from "next";
import "./globals.css";
import { BoardProvider } from "@/context/BoardContext/BoardContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='h-screen p-6 lg:p-16 bg-slate-50'>
        <div className="md:max-w-screen-xl mx-auto">
          <BoardProvider>{children}</BoardProvider>
          </div>
        </body>
    </html>
  );
}
